set runtimepath^=$XDG_CONFIG_HOME/vim runtimepath+=$XDG_CONFIG_HOME/vim/after
let &packpath = &runtimepath
let vim_dir = "$XDG_CONFIG_HOME/vim"

set nocompatible
syntax on

mapclear " "
let mapleader=" "
let maplocalleader=" "

call plug#begin()
Plug 'godlygeek/tabular'
Plug 'kovetskiy/sxhkd-vim'
Plug 'lervag/vimtex',				{ 'for' : 'tex' }
"Plug 'scrooloose/syntastic'
"Plug 'scrooloose/nerdtree'
Plug 'dense-analysis/ale'
Plug 'hura/vim-asymptote',			{ 'for' : 'asy' }
Plug 'kovisoft/slimv',				{ 'for' : 'lisp' }
Plug 'plasticboy/vim-markdown',		{ 'for' : 'markdown' }
Plug 'thinca/vim-quickrun'
"Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'vimlab/split-term.vim'
Plug 'sirver/ultisnips',			
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ryanoasis/vim-devicons'
"Plug 'puremourning/vimspector'

"if has('nvim')
"	Plug 'shougo/deoppet.nvim'
"endif
call plug#end()

"Agda
"au BufWritePost *.lagda execute "normal! :CornelisLoad\<CR>"


filetype off
set undofile
set undodir=$XDG_STATE_HOME/nvim/undo_nvim

set foldenable
set foldmethod=indent
set scrolloff=4
set autoread 
set wildmenu
set laststatus=2
set hlsearch
set tabstop=4
set softtabstop=4
set shiftwidth=4
set showcmd
set mouse=


let g:NERDTreeDirArrowExpandable=''
let g:NERDTreeDirArrowCollapsible=''

let g:lisp_rainbow=1
let g:paredit_mode=0
let g:slimv_leader='\'

let g:syntastic_cpp_check_header=1
let g:syntastic_warning_symbol='>'
let g:syntastic_error_symbol='>>'

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0

let g:vimtex_log_verbose=1
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
"let g:vimtex_syntax_packages = {'amsmath': 2, 'asymptote': 2}
let g:UltiSnipsExpandTrigger = '<tab>'			
let g:UltiSnipsJumpForwardTrigger = '<tab>'		
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'	
let g:tex_conceal='abdmgs'

" Because Ctrl-W is kinda hard
nnoremap <leader>l l
nnoremap <leader>h h
nnoremap <leader>j j
nnoremap <leader>k k
nnoremap <leader>L L
nnoremap <leader>H H
nnoremap <leader>J J
nnoremap <leader>K K
nnoremap <leader>< <
nnoremap <leader>> >
nnoremap <leader>o o
nnoremap <leader>s s
nnoremap <leader>bn :bn<CR>
nnoremap <leader>bp :bp<CR>

nnoremap <leader>t :NERDTreeToggle<CR>
nnoremap <silent> <leader>n :noh<CR>
nnoremap <leader>r :QuickRun<CR>
nnoremap Y y$

nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

"I sometimes accidentally scroll on touchpad,
"so disable arrow keys (which also disables
"mouse scrolling)
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;

nnoremap <CR> :wa<CR>:w<CR>
nnoremap Q :q<CR>


set number norelativenumber
" Use relative numbers while in normal mode in a buffer
"augroup numbertoggle
"	autocmd!
"	autocmd BufEnter,FocusGained,InsertLeave * set number relativenumber
"	autocmd BufLeave,FocusLost,InsertEnter * set number norelativenumber
"augroup END

filetype plugin indent on

let g:airline#extensions#ale#enabled = 1

let g:airline_theme='violet'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#vimtex#enabled = 1
let g:airline_powerline_fonts = 1
let g:webdevicons_enable_airline_tabline = 1
let g:webdevicons_enable_airline_statusline = 1

if (empty($TMUX))
  if (has("nvim"))
  "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif
colorscheme slate

"Slate is nice, except the paren highlighting is atrocious
hi MatchParen guifg=#cccccc guibg=#008b8b gui=NONE cterm=NONE


let g:ale_haskell_ghc_options = '-fno-code -v0 -dynamic'
function! LinterStatus() abort
    let l:counts = ale#statusline#Count(bufnr(''))

    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors

    return l:counts.total == 0 ? 'OK' : printf(
    \   '%dW %dE',
    \   all_non_errors,
    \   all_errors
    \)
endfunction

set statusline=%{LinterStatus()}

